/**
 * Patient Repository API
 * Demo for RESTful API created with Spring Boot with OpenAPI documentation.
 *
 * OpenAPI spec version: 2.3.0.RELEASE
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class Patient {
  readonly id: number;
  /**
   * Name of the patient
   */
  name: string;
  /**
   * Name of the project
   */
  project?: string;
  /**
   * Name of the archive
   */
  archive?: string;
  /**
   * Name of an attachment
   */
  attachment?: string;
}
